FROM node:20-alpine AS build

WORKDIR /app
COPY apps/web/package*.json ./apps/web/
RUN cd apps/web && npm install

COPY apps/web ./apps/web
RUN cd apps/web && npm run build

FROM nginx:alpine
COPY infra/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/apps/web/dist /usr/share/nginx/html

EXPOSE 80
