FROM python:3.12-slim

WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY . /app
ENV RUN_MODE=prod
EXPOSE 8000

CMD ["python", "scripts/run_api.py"]
